# Create Simple EC2

AWSTemplateFormatVersion: '2010-09-09'
Description: Create EC2 instance
Resources:
  MyEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.medium
      ImageId: ami-091138d0f0d41ff90
      KeyName: Demo
      SecurityGroupIds:
        - sg-0014e2d211f0a4462
      Tags:
        - Key: Name 
          Value: MySimpleEc2  #Assigns name to EC2 instance
