AWSTemplateFormatVersion: "2010-09-09"
Description: Install Apache Web Server using UserData on EC2

Resources:
  UserDataEc2:
    Type: AWS::EC2::Instance

    Properties:
      InstanceType: t3.medium
      KeyName: Demo
      ImageId: ami-00e801948462f718a

      SecurityGroupIds:
        - sg-0014e2d211f0a4462

      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum update -y
          sudo yum install httpd -y
          sudo systemctl start httpd
          sudo systemctl enable httpd
          echo "Hello World" > /var/www/html/index.html
