AWSTemplateFormatVersion: "2010-09-09"
Description: Parent Stack

Resources:

  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cloudformationstackspractice.s3.us-east-1.amazonaws.com/VPCStack.yaml

  ComputeStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: https://cloudformationstackspractice.s3.us-east-1.amazonaws.com/EC2Stack.yaml

      Parameters:
        VPCId:
          !GetAtt VPCStack.Outputs.VPCId

        SubnetId:
          !GetAtt VPCStack.Outputs.PublicSubnetId

  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: https://cloudformationstackspractice.s3.us-east-1.amazonaws.com/RDSStack.yaml

      Parameters:
        VPCId:
          !GetAtt VPCStack.Outputs.VPCId
