AWSTemplateFormatVersion: "2010-09-09"
Description: Parent Stack

Resources:

  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://us-east-1.console.aws.amazon.com/s3/object/cloudformationstackspractice?region=us-east-1&prefix=VPCStack.yaml

  ComputeStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: https://us-east-1.console.aws.amazon.com/s3/object/cloudformationstackspractice?region=us-east-1&prefix=EC2Stack.yaml

      Parameters:
        VPCId:
          !GetAtt VPCStack.Outputs.VPCId

        SubnetId:
          !GetAtt VPCStack.Outputs.PublicSubnetId

  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: https://us-east-1.console.aws.amazon.com/s3/object/cloudformationstackspractice?region=us-east-1&prefix=RDSStack.yaml

      Parameters:
        VPCId:
          !GetAtt VPCStack.Outputs.VPCId
